### ISSUE TITLE
Sms is always sent via System number

### ISSUE THREAD

**Issue by Lumeriol** [BulkGate/php-sdk#1]
I was upgrade deprecated Nette SDK to this library, but I have simple problem. All messages are sent as system number, even if all is set for Text Sender or Short Code. I tried to set it via Sms->configure(), Sms->settings->configure or MessageSender configurator, send message return type show me correctly that sender_id is gText, (sender_id_value has 11 characters), but in Portal and incoming SMS is only system number.
Also try to set a new API in Portal (PHP SDK) instead old Nette SDK, but nothing was changed.

So, until this will be fixed, I must turn back to old SDK, where everything was correct.

**Comment by lukaspijak** [comment]
Thanks to report, I try to fix it today.

**Comment by lukaspijak** [comment]
The problem was fixed. It was problem on our API, you don't have to upgrade SDK. 

Can you confirm the issue is resolved?

**Comment by Lumeriol** [comment]
Confirmed, problem was fixed and now SMS is sent correctly as Text sender.

Thank you for quick response.
