### ISSUE TITLE
Option to check credits

### ISSUE THREAD

**Issue by juniwalk** [BulkGate/php-sdk#2]
Hello,
are there any plans to add option to check credits or will this be only available in HTTP api?

**Comment by lukaspijak** [comment]
Hello, unfortunately the SDK does not have native support for this feature. You need to use the API https://help.bulkgate.com/docs/en/http-simple-check-credit-balance.html 

We will also try to add this feature to the SDK or you can send PR.

**Comment by juniwalk** [comment]
> We will also try to add this feature to the SDK or you can send PR.

Alright I am just looking for options so if I end up implementing this I will try to send PR with balance checking.

**Comment by lukaspijak** [comment]
I just added new integration API endpoint for this feature `https://portal.bulkgate.com/api/1.0/integration/info`

Now you can call this:

```php
$response = $this->connection->send(new Connection\Request('info', new Message\Api([])));
```

**Comment by juniwalk** [comment]
Thank you

**Comment by lukaspijak** [comment]
I added new [CreditChecker](https://github.com/BulkGate/php-sdk/blob/main/src/CreditChecker.php) class for check credit. Does it meet your requirements?

**Comment by juniwalk** [comment]
Looks great, I didn't get a chance to try it yet.

**Comment by Lumeriol** [comment]
Simple to use and gets all needed information, thanks for implementation 👍

**Comment by lukaspijak** [comment]
New version released https://github.com/BulkGate/php-sdk/releases/tag/1.0.1
