### ISSUE TITLE
How to set Delivery confirmations or webhook URL for delivery reports.

### ISSUE THREAD

**Issue by klytron** [BulkGate/php-sdk#3]
Where and how do I set the URL to receive Delivery confirmations?

It is not clear reading: https://help.bulkgate.com/docs/en/http-low-level-api-delivery-confirmations-and-incoming-sms.html#delivery-confirmation-parameters

**Comment by lukaspijak** [comment]
Hello,

you must go to our [Portal](https://portal.bulkgate.com/application/). And go to left menu:

**Modules & APIs** > **Select your created application**  > **Delivery reports** > **URL delivery reports** > "**+**"

![image](https://github.com/BulkGate/php-sdk/assets/2571714/d6e834c5-fa47-4e0f-9e2e-6532b937d681)

Your URL must be available from our portal. 

![image](https://github.com/BulkGate/php-sdk/assets/2571714/dfbc0c85-131f-4026-9d8c-958b59de4846)
